from dataclasses import dataclass



@dataclass(eq=False)
class PLAYER_DEFAULTS:
    output_json_keys = ['playerId', 
                        'isActive', 
                        'currentTeamId', 
                        'currentTeamAbbrev',
                        'fullTeamName', 
                        'teamCommonName', 
                        'teamPlaceNameWithPreposition',
                        'firstName', 
                        'lastName', 
                        'badges', 
                        'teamLogo', 
                        'sweaterNumber',
                        'position', 
                        'headshot', 
                        'heroImage', 
                        'heightInInches',
                        'heightInCentimeters', 
                        'weightInPounds', 
                        'weightInKilograms',
                        'birthDate', 
                        'birthCity', 
                        'birthStateProvince', 
                        'birthCountry',
                        'shootsCatches', 
                        #'draftDetails', 
                        #'playerSlug', 
                        #'inTop100AllTime',
                        #'inHHOF', 
                        #'featuredStats', 
                        #'careerTotals', 
                        #'shopLink', 
                        #'twitterLink',
                        #'watchLink', 
                        #'seasonTotals'
                        ]
    

@dataclass(eq=False)
class EVENT_DEFAULTS:
    output_json_keys = ['id', 
                        'eventId', 
                        'period', 
                        'timeInPeriod', 
                        'secondsRemaining',
                        'situationCode', 
                        'typeCode', 
                        'typeDescKey', 
                        'homeTeamDefendingSide',
                        'sortOrder', 
                        'utc', 
                        'eventOwnerTeamId', 
                        'losingPlayerId',
                        'winningPlayerId', 
                        'xCoord', 
                        'yCoord', 
                        'zoneCode', 
                        'playerId',
                        'shotType', 
                        'shootingPlayerId', 
                        'goalieInNetId', 
                        'awaySOG', 
                        'homeSOG',
                        'hittingPlayerId', 
                        'hitteePlayerId', 
                        'blockingPlayerId', 
                        'reason',
                        'penaltyTypeCode', 
                        'descKey', 
                        'duration', 
                        'committedByPlayerId',
                        'drawnByPlayerId', 
                        'goalModifier', 
                        'strength', 
                        'scoringPlayerId',
                        'assist1PlayerId', 
                        'assist2PlayerId', 
                        'awayScore', 
                        'homeScore',
                        'strengthCode', 
                        'goalCode', 
                        'scoringPlayerTotal', 
                        'assist1PlayerTotal',
                        'assist2PlayerTotal', 
                        'servedByPlayerId']
    


@dataclass(eq=False)
class GAME_DEFAULTS:
    output_json_keys = ['id', 
                        'season', 
                        'gameType', 
                        'gameDate', 
                        'venue', 
                        'neutralSite',
                        'startTimeUTC',
                        'easternUTCOffset', 
                        'venueUTCOffset', 
                        'venueTimezone',
                        'gameState', 
                        'gameScheduleState', 
                        #'tvBroadcasts', 
                        #'awayTeam',
                        #'homeTeam', 
                        'periodDescriptor', 
                        #'gameOutcome', 
                        #'winningGoalie',
                        'threeMinRecap', 
                        'threeMinRecapFr', 
                        'condensedGame', 
                        'condensedGameFr',
                        #'gameCenterLink', 
                        #'winningGoalScorer', 
                        #'seriesStatus', 
                        #'seriesUrl',
                        #'ticketsLink', 
                        #'ticketsLinkFr',
                        # added
                        'awayTeamId',
                        'homeTeamId',
                        'winningGoalieId',
                        'winningGoalScorerId',
                        'periodType'

                        ]

